production:
  solr:
    hostname: index.websolr.com
    port: 80
    path: /solr/1e6e34fbf46
    log_level: WARNING
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
